build: depend on libm
On Ubuntu, the linking fails without libm:

	/usr/bin/ld: src/25a6634@@gnome-2048@exe/meson-generated_view.c.o: undefined reference to symbol 'ceilf@@GLIBC_2.2.5'
	/usr/bin/ld: //lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
	collect2: error: ld returned 1 exit status